function inputField = createNumericInput(container, options)
    % CREATENUMERICINPUT Create a numeric input and return its handle (Static Method)
    %
    % The returned handle is for the uieditfield object that contains the
    % user-entered value; get or set this value using `inputField.Value`.
    %
    % If the provided value is the string "Inf" it is converted to the number Inf.
    arguments
        container  % must be a grid container (uigridlayout)
        options.Label = "Input Label"
        options.Units = ""
        options.Value = 0
        options.LowerLimit = -Inf
        options.UpperLimit = Inf
        options.LowerLimitInclusive = "on"
        options.UpperLimitInclusive = "on"
        options.DisplayFormat = "%11.4g"
        options.IsInteger = false
    end

    if ~isnumeric(options.Value) && options.Value == "Inf"
        options.Value = Inf;
    end

    uilabel(                            ...
        container,                      ...
        "Text", options.Label,          ...
        "HorizontalAlignment", "right"  ...
    );
    inputField = uieditfield(                                ...
        container,                                           ...
        "numeric",                                           ...
        "Limits", [options.LowerLimit, options.UpperLimit],  ...
        "LowerLimitInclusive", options.LowerLimitInclusive,  ...
        "UpperLimitInclusive", options.UpperLimitInclusive,  ...
        "RoundFractionalValues", options.IsInteger,          ...
        "ValueDisplayFormat", options.DisplayFormat,         ...
        "Value", options.Value                               ...
    );
    uilabel(                   ...
        container,             ...
        "Text", options.Units  ...
    );
end
