function clearSolution(obj)
    % CLEARSOLUTION Remove all stored solution values
    obj.isSolutionAvailable = false;

    obj.odeSol = [];
    obj.residuals = [];

    obj.V_k = [];
    obj.V_r = [];
    obj.V_l = [];

    obj.T_k = [];
    obj.T_r_cold = [];
    obj.T_r = [];
    obj.T_r_hot = [];
    obj.T_l = [];

    obj.P_ave = [];

    obj.freq = [];
    obj.period = [];

    obj.indicatedPowerZeroDP = [];
    obj.indicatedPower = [];
    obj.shaftPower = [];
    obj.shaftTorque = [];
    obj.netPower = [];
    obj.heatInput = [];
    obj.efficiency = [];

    % Reset the state values struct
    obj.stateValues = struct(  ...
        "time", [],            ...
        "T_c", [],             ...
        "T_e", [],             ...
        "P", [],               ...
        "m_dot_ck", [],        ...
        "m_dot_kr", [],        ...
        "m_dot_rl", [],        ...
        "m_dot_le", [],        ...
        "Q_dot_k", [],         ...
        "Q_dot_r", [],         ...
        "Q_dot_l", [],         ...
        "dTc_dt", [],          ...
        "dTe_dt", [],          ...
        "dP_dt", []            ...
    );
end
